### ISSUE TITLE
Research and Map Governance Events by Contract and Network

### ISSUE THREAD

**Issue by 0xSero** [zksync-association/zksync-rss#1]
## Objective:

Determine all contract events that need monitoring, aligning them with relevant ZKsync and Ethereum networks.

### Subtasks:

- [x] List each event to be tracked, ensuring coverage of governance-specific actions (e.g., Proposal Submitted, Voting Period Started).
- [x] Map events to a structured data model for consistency (i.e., assign titles, descriptions, and category tags as defined in the RSS spec)

Priority: High – foundational to the monitoring system.
### Resources:

- [x] Token:
    - [x] ZK Token: [0x5A7d6b2F92C77FAD6CCaBd7EE0624E64907Eaf3E](https://explorer.zksync.io/address/0x5A7d6b2F92C77FAD6CCaBd7EE0624E64907Eaf3E)
- [x] ZkProtocolGovernor
    - [x] Governor: [0x76705327e682F2d96943280D99464Ab61219e34f](https://explorer.zksync.io/address/0x76705327e682F2d96943280D99464Ab61219e34f)
    - [x] Timelock: [0x3701fB675bCd4A85eb11A2467628BBe193F6e6A8](https://explorer.zksync.io/address/0x3701fB675bCd4A85eb11A2467628BBe193F6e6A8)
- [x] ZkTokenGovernor
    - [x] Governor: [0x10560f8B7eE37571AD7E3702EEb12Bc422036E89](https://explorer.zksync.io/address/0x10560f8B7eE37571AD7E3702EEb12Bc422036E89)
    - [x] Timelock: [0x3E21c654B545Bf6236DC08236169DcF13dA4dDd6](https://explorer.zksync.io/address/0x3E21c654B545Bf6236DC08236169DcF13dA4dDd6)
- [x] ZkGovOpsGovernor
    - [x] Governor: [0x496869a7575A1f907D1C5B1eca28e4e9E382afAb](https://explorer.zksync.io/address/0x496869a7575A1f907D1C5B1eca28e4e9E382afAb)
    - [x] Timelock: [0xC3e970cB015B5FC36edDf293D2370ef5D00F7a19](https://explorer.zksync.io/address/0xC3e970cB015B5FC36edDf293D2370ef5D00F7a19)
- [x] Protocol Upgrade Handler address: [0x8f7a9912416e8AdC4D9c21FAe1415D3318A11897](https://etherscan.io/address/0x8f7a9912416e8AdC4D9c21FAe1415D3318A11897)
- [x] Emergency Upgrade Board address: [0xdEFd1eDEE3E8c5965216bd59C866f7f5307C9b29](https://etherscan.io/address/0xdEFd1eDEE3E8c5965216bd59C866f7f5307C9b29)
- [x] Guardians address: [0xD677e09324F8Bb3cC64F009973693f751c33A888](https://etherscan.io/address/0xD677e09324F8Bb3cC64F009973693f751c33A888)
- [x] Security Council address: [0xBDFfCC71FE84020238F2990a6D2954e87355De0D](https://etherscan.io/address/0xBDFfCC71FE84020238F2990a6D2954e87355De0D)
- [x] Foundation address: [0xbC1653bd3829dfEc575AfC3816D4899cd103B51c](https://etherscan.io/address/0xbC1653bd3829dfEc575AfC3816D4899cd103B51c)
- [x] CHANGELOG: [zkMessage](https://explorer.zksync.io/address/0x5d89444f84d544deBbD13D672f314A4DfaE3f77C#transactions)
