### ISSUE TITLE
Build Event Monitor

### ISSUE THREAD

**Issue by 0xSero** [zksync-association/zksync-rss#3]
## Objective:

Set up a monitoring script to scan for contract events, [itemize them](https://github.com/ScopeLift/zksync-rss/issues/2), and populate the RSS feed.

### Subtasks:

- [x] Implement a polling mechanism for ZKsync and Ethereum governance contracts based on events in Task 1.
- [x] For each event detected:
    - Itemize the event data into XML format.
    - Update the RSS feed with new items.
- [x] Handle errors:
    - Add exponential backoff polling with up to three retries if scan fails.
    - After three failed attempts, throw error.
- [x] Allow the process to be started from an arbitrary block
    
### Resources and specifics:
- Will require an RPC
- Ethers or Wagmi for contract instantiation
- Run every 10 minutes
- Promise.all() to minimize runtime
- Make compatible with GCP cloud functions
