### ISSUE TITLE
Document Functionality for Handoff

### ISSUE THREAD

**Issue by 0xSero** [zksync-association/zksync-rss#4]
### Objective:

Provide clear documentation for maintenance, usage, and handoff.

### Subtasks:

- [x] Document dependencies, envs, and costs for running service (hosting + rpc)
- [x] Document components of system (Monitor, Event Itemization, Constants, Error handling)
- [x] Write small guide for expanding system by adding new contracts, events, and networks

### Output: Clearly defined docs for costs, deps, and guide on improving system
