### ISSUE TITLE
Build Minimal Site to Display RSS Feed

### ISSUE THREAD

**Issue by 0xSero** [zksync-association/zksync-rss#5]
## Objective:

Build a simple site to consume and display the RSS feed entries

### Subtasks:

- [x] Site should be minimal complexity, preferably just javascript or react
- [x] RSS text content, Black with white text
    - Example: https://folklore-cms.vercel.app/entries.rss
- [x] Make compatible with hosting on GCP

### Resources:

- Example repo: https://github.com/whitep4nth3r/thingoftheday/blob/main/functions/rss.js
